export const productGroups = [
  { id: 'heat-treatment', label: '열처리', en: 'Heat Treatment', hero: '/assets/images/video-flange-hub.png', description: '부품 형상과 목표 경화층을 기준으로 전원·코일·냉각·이송을 통합 설계합니다.', items: [['out-shaft', 'OUT SHAFT 열처리·템퍼링 M/C'], ['in-shaft', 'IN SHAFT 열처리·템퍼링 M/C'], ['flange', 'FLANGE 열처리 M/C'], ['cam-shaft', 'CAM-SHAFT 열처리 M/C'], ['shaft', 'SHAFT 열처리·템퍼링 M/C'], ['steering', '조향장치 열처리·템퍼링 M/C'], ['gear-spindle', 'GEAR / SPINDLE 열처리 M/C'], ['multi-axis', '다축 동시 열처리 자동화 M/C']] },
  { id: 'brazing', label: '브레이징', en: 'Brazing', hero: '/assets/images/hero-solutions-integrated.png', description: '접합부 형상과 소재 조합에 맞춘 코일, 지그, 온도 조건으로 반복 품질을 관리합니다.', items: [['carbide', 'CARBIDE TOOL 브레이징 M/C'], ['pcd-tip', 'PCD TIP 브레이징 M/C'], ['end-mill', 'END MILL 브레이징 M/C'], ['drill', 'DRILL 브레이징 M/C'], ['pipe-fitting', 'PIPE / FITTING 브레이징 M/C'], ['multi-station', '다공정 자동 브레이징 M/C']] },
  { id: 'heating', label: '가열기', en: 'High Frequency Heater', hero: '/assets/images/hero-applications-components.png', description: '압입·단조·성형 등 생산 조건에 맞는 유도가열 시스템을 맞춤 구성합니다.', items: [['motor-case', 'MOTOR CASE 가열기'], ['shrink-fit', '열간 압입 가열기'], ['gear-shaft-heater', 'GEAR SHAFT 가열기'], ['porous-metal', 'POROUS METAL 가열기'], ['medical-experimental', '실험용 정밀 가열기'], ['drill-endmill', 'DRILL & ENDMILL 가열기'], ['mobile-phone-case', 'MOBILE PHONE CASE 가열기'], ['forging', 'FORGING 가열기'], ['speaker-grill', 'SPEAKER GRILL 가열기'], ['remote-controller', 'REMOTE CONTROLLER 가열기'], ['molding-insert', 'MOLDING INSERT 가열기']] }
];

const productImages = {
  'out-shaft': '/assets/images/products/end-mill.jpg', 'in-shaft': '/assets/images/products/in-shaft.jpg', flange: '/assets/images/products/flange.jpg', 'cam-shaft': '/assets/images/products/cam-shaft.jpg', shaft: '/assets/images/products/gear-spindle.jpg', steering: '/assets/images/products/speaker-grill.jpg', 'gear-spindle': '/assets/images/products/gear-spindle.jpg', 'multi-axis': '/assets/images/products/multi-axis.jpg', carbide: '/assets/images/products/drill.jpg', 'pcd-tip': '/assets/images/products/pcd-tip.jpg', 'end-mill': '/assets/images/products/end-mill.jpg', drill: '/assets/images/products/drill-endmill.jpg', 'pipe-fitting': '/assets/images/products/remote-controller.jpg', 'multi-station': '/assets/images/products/multi-axis.jpg', 'motor-case': '/assets/images/products/motor-case-01.jpg', 'shrink-fit': '/assets/images/products/shrink-fit-02.jpg', 'gear-shaft-heater': '/assets/images/products/gear-shaft-heater.jpg', 'porous-metal': '/assets/images/products/forging.jpg', 'medical-experimental': '/assets/images/products/motor-case-02.jpg', 'drill-endmill': '/assets/images/products/drill-endmill.jpg', 'mobile-phone-case': '/assets/images/products/mobile-phone-case.jpg', forging: '/assets/images/products/forging.jpg', 'speaker-grill': '/assets/images/products/speaker-grill.jpg', 'remote-controller': '/assets/images/products/remote-controller.jpg', 'molding-insert': '/assets/images/products/shrink-fit-03.jpg'
};

export function productImage(slug, fallback) { return productImages[slug] || fallback; }

export function findProduct(category, slug) { const group = productGroups.find((item) => item.id === category); const item = group?.items.find(([id]) => id === slug); return group && item ? { group, slug: item[0], title: item[1] } : null; }
