export const productGroups = [
  { id: 'heat-treatment', label: '열처리', en: 'Heat Treatment', hero: '/assets/images/video-flange-hub.png', description: '부품 형상과 목표 경화층을 기준으로 전원·코일·냉각·이송을 통합 설계합니다.', items: [['out-shaft', 'OUT SHAFT 열처리·템퍼링 M/C'], ['in-shaft', 'IN SHAFT 열처리·템퍼링 M/C'], ['flange', 'FLANGE 열처리 M/C'], ['cam-shaft', 'CAM-SHAFT 열처리 M/C'], ['shaft', 'SHAFT 열처리·템퍼링 M/C'], ['steering', '조향장치 열처리·템퍼링 M/C'], ['gear-spindle', 'GEAR / SPINDLE 열처리 M/C'], ['multi-axis', '다축 동시 열처리 자동화 M/C']] },
  { id: 'brazing', label: '브레이징', en: 'Brazing', hero: '/assets/images/products/brazing/multi-station.webp', description: '접합부 형상과 소재 조합에 맞춘 코일, 지그, 온도 조건으로 반복 품질을 관리합니다.', items: [['carbide', 'CARBIDE TOOL 브레이징 M/C'], ['pcd-tip', 'PCD TIP 브레이징 M/C'], ['end-mill', 'END MILL 브레이징 M/C'], ['drill', 'DRILL 브레이징 M/C'], ['pipe-fitting', 'PIPE / FITTING 브레이징 M/C'], ['multi-station', '다공정 자동 브레이징 M/C']] },
  { id: 'heating', label: '가열기', en: 'High Frequency Heater', hero: '/assets/images/products/heating/heating-04.webp', description: '압입·단조·성형 등 생산 조건에 맞는 유도가열 시스템을 맞춤 구성합니다.', items: [['motor-case-01', 'MOTOR CASE 가열기 · 내경 가열'], ['motor-case-02', 'MOTOR CASE 가열기 · 대형 하우징'], ['shrink-fit-01', '열간 압입 가열기 · 링/슬리브'], ['gear-shaft-heater', 'GEAR SHAFT 가열기'], ['shrink-fit-02', '열간 압입 가열기 · 정밀 링'], ['shrink-fit-03', '열간 압입 가열기 · 플랜지/허브'], ['porous-metal', 'POROUS METAL 가열기'], ['medical-experimental', '실험용 정밀 가열기'], ['drill-endmill', 'DRILL & ENDMILL 가열기'], ['mobile-phone-case', 'MOBILE PHONE CASE 가열기'], ['motor-case-03', 'MOTOR CASE 가열기 · 자동화'], ['forging', 'FORGING 가열기'], ['speaker-grill', 'SPEAKER GRILL 가열기'], ['remote-controller', 'REMOTE CONTROLLER 가열기'], ['molding-insert', 'MOLDING INSERT 가열기']] }
];

const productImages = {
  'out-shaft': '/assets/images/products/end-mill.jpg', 'in-shaft': '/assets/images/products/in-shaft.jpg', flange: '/assets/images/products/flange.jpg', 'cam-shaft': '/assets/images/products/cam-shaft.jpg', shaft: '/assets/images/products/gear-spindle.jpg', steering: '/assets/images/products/speaker-grill.jpg', 'gear-spindle': '/assets/images/products/gear-spindle.jpg', 'multi-axis': '/assets/images/products/multi-axis.jpg', carbide: '/assets/images/products/brazing/carbide-tool.webp', 'pcd-tip': '/assets/images/products/brazing/pcd-tip.webp', 'end-mill': '/assets/images/products/brazing/end-mill.webp', drill: '/assets/images/products/brazing/drill.webp', 'pipe-fitting': '/assets/images/products/brazing/pipe-fitting.webp', 'multi-station': '/assets/images/products/brazing/multi-station.webp', 'motor-case-01': '/assets/images/products/heating/heating-01.webp', 'motor-case-02': '/assets/images/products/heating/heating-02.webp', 'shrink-fit-01': '/assets/images/products/heating/heating-03.webp', 'gear-shaft-heater': '/assets/images/products/heating/heating-04.webp', 'shrink-fit-02': '/assets/images/products/heating/heating-05.webp', 'shrink-fit-03': '/assets/images/products/heating/heating-06.webp', 'porous-metal': '/assets/images/products/heating/heating-07.webp', 'medical-experimental': '/assets/images/products/heating/heating-08.webp', 'drill-endmill': '/assets/images/products/heating/heating-09.webp', 'mobile-phone-case': '/assets/images/products/heating/heating-10.webp', 'motor-case-03': '/assets/images/products/heating/heating-11.webp', forging: '/assets/images/products/heating/heating-12.webp', 'speaker-grill': '/assets/images/products/heating/heating-13.webp', 'remote-controller': '/assets/images/products/heating/heating-14.webp', 'molding-insert': '/assets/images/products/heating/heating-15.webp'
};

export function productImage(slug, fallback) { return productImages[slug] || fallback; }

export function findProduct(category, slug) { const group = productGroups.find((item) => item.id === category); const item = group?.items.find(([id]) => id === slug); return group && item ? { group, slug: item[0], title: item[1] } : null; }
